# Generated by Django 3.1.5 on 2021-03-04 07:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import funmizesub.utilis


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
                ('referral_id', models.CharField(max_length=70)),
                ('bankname', models.CharField(max_length=70)),
                ('acct_name', models.CharField(max_length=70)),
                ('acct_number', models.CharField(max_length=70)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Networkplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_balance', models.FloatField()),
                ('old_balance', models.FloatField()),
                ('amount_added', models.FloatField()),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funmizesub.customer')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('reference_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('prebal', models.IntegerField(blank=True, null=True)),
                ('postbal', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction_History',
                'verbose_name_plural': 'Transaction_Historys',
                'db_table': 'Transaction_Historys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Planamount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('network_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funmizesub.networkplan')),
            ],
        ),
        migrations.CreateModel(
            name='Addbalancetouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_add', models.IntegerField()),
                ('refcode', models.CharField(default=funmizesub.utilis.refcode, max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
