# Generated by Django 3.1.5 on 2021-03-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funmizesub', '0004_transhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction_History',
        ),
    ]
