# Generated by Django 3.1.5 on 2021-03-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funmizesub', '0007_payhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planamount',
            name='network_type',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Addbalancetouser',
        ),
        migrations.DeleteModel(
            name='Planamount',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
